apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-python-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/shahgnp/demo-python-app:*
spec:
  destination:
    namespace: demo-python-app
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/shahGnp/helm_demo-python-app'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
